### ISSUE TITLE
[Overview] "Because DIDs reside on a distributed ledger" - not true?

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-spec#17]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/119)

**Comment by msporny** [comment]
I believe this issue has been fixed. Please confirm @rhiaro.

**Comment by rhiaro** [comment]
Yes, that paragraph was rewritten and that implication is no longer there.

**Comment by msporny** [comment]
Stale issue, editorial, closing.
