### ISSUE TITLE
[Introduction] Doesn't read well...

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-spec#43]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/220)

**Comment by msporny** [comment]
I believe this issue has been resolved. @rhiaro, can you please verify?

**Comment by rhiaro** [comment]
Original issue is resolved, but followup comment (very small editorial improvement) has not been done:

> In the new wording, change `on `to `to`.  Also add an `on`.

>> The difference is that a DID Method specification, in addition to defining a specific DID scheme, also specifies the methods for resolving and deactivating DIDs `on` and writing DID Documents `to` the appropriate DID Registry.
