### ISSUE TITLE
Random capitalization of "key terms" ...those that appear in the Terminology section

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-spec#50]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/269)

**Comment by peacekeeper** [comment]
I started to work on capitalization of key terms in https://github.com/w3c/did-spec/commit/266b2b620155d5eaf314c24b0975029293d27ce4, but am a bit undecided on what terms we want in uppercase/lowercase. E.g. I suspect most people in the community would write "DID **S**ubject" (uppercase), but "DID **s**cheme" or "DID **p**ath" (lowercase). For some terms, I see both versions frequently in the community, e.g. "DID **D/d**ocument" or "DID **M/m**ethod".

The Verifiable Credentials spec seems to use lower case terms consistently, perhaps we should adopt that same approach.

**Comment by brentzundel** [comment]
I think lower case terms are best, especially if we can link them to their definition in the spec.

**Comment by peacekeeper** [comment]
I agree with @brentzundel to do lower case for defined terms. I opened #73 to make that change. I propose that we then create a separate PR to add missing links for all defined terms.
