### ISSUE TITLE
What happened to the "old" list of did-spec issues?

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-spec#6]
...are they lost?

**Comment by peacekeeper** [comment]
@mwherman2000 they are not lost, they are still where they have always been: https://github.com/w3c-ccg/did-spec/issues

The chairs and members of the new WG are currently discussing how to transfer commits, issues and PRs from the "old" CCG repo into this new repo.

**Comment by msporny** [comment]
At this point, all issues on the CCG version of the DID spec have been transferred to this repository for further processing by the DID WG.

Closing this issue as resolved (all the "old" issues are here now).
